
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvxAndroidFragmentsTest.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvxAndroidFragmentsTest.Core.Resources.CoreResources", typeof(CoreResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modificare un&apos;attività o premere indietro..
        /// </summary>
        internal static string alert_activities_notchanged_msg {
            get {
                return ResourceManager.GetString("alert_activities_notchanged_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungere una nota o premere indietro..
        /// </summary>
        internal static string alert_comments_notchanged_msg {
            get {
                return ResourceManager.GetString("alert_comments_notchanged_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione!.
        /// </summary>
        internal static string alert_generic_title {
            get {
                return ResourceManager.GetString("alert_generic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apportare delle modifiche o premere indietro..
        /// </summary>
        internal static string alert_notmodified_msg {
            get {
                return ResourceManager.GetString("alert_notmodified_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegliere uno status o premere indietro..
        /// </summary>
        internal static string alert_status_notchanged_msg {
            get {
                return ResourceManager.GetString("alert_status_notchanged_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per procedere è necessario impostare l&apos;indirizzo del server di sincronizzazione. Accedere alle impostazioni..
        /// </summary>
        internal static string alert_syncservernotsetted_msg {
            get {
                return ResourceManager.GetString("alert_syncservernotsetted_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compilare tutti i campi necessari o premere indietro..
        /// </summary>
        internal static string alert_validation_error_msg {
            get {
                return ResourceManager.GetString("alert_validation_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Eliminare tutti i filtri impostati?.
        /// </summary>
        internal static string confirm_clear_filters_title {
            get {
                return ResourceManager.GetString("confirm_clear_filters_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione di logout. Riprovare..
        /// </summary>
        internal static string confirm_logout_error {
            get {
                return ResourceManager.GetString("confirm_logout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Effettuare il logout?.
        /// </summary>
        internal static string confirm_logout_title {
            get {
                return ResourceManager.GetString("confirm_logout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione di download del documento. Riprovare..
        /// </summary>
        internal static string confirm_proceed_sign_error {
            get {
                return ResourceManager.GetString("confirm_proceed_sign_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; presente un documento già firmato per l&apos;ODL corrente. Aggiungere una firma al documento precedente? Le eventuali modifiche apportate ai dati non saranno presenti. In caso contrario verrà firmato un nuovo documento aggiornato..
        /// </summary>
        internal static string confirm_proceed_sign_msg {
            get {
                return ResourceManager.GetString("confirm_proceed_sign_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Documento firmato già presente.
        /// </summary>
        internal static string confirm_proceed_sign_title {
            get {
                return ResourceManager.GetString("confirm_proceed_sign_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Articolo.
        /// </summary>
        internal static string docType_article {
            get {
                return ResourceManager.GetString("docType_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Costo.
        /// </summary>
        internal static string docType_cost {
            get {
                return ResourceManager.GetString("docType_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resource Type.
        /// </summary>
        internal static string docType_hour {
            get {
                return ResourceManager.GetString("docType_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo non presente..
        /// </summary>
        internal static string err_address_missing_msg {
            get {
                return ResourceManager.GetString("err_address_missing_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile localizzare il cliente..
        /// </summary>
        internal static string err_address_missing_title {
            get {
                return ResourceManager.GetString("err_address_missing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;eliminazione dei filtri..
        /// </summary>
        internal static string err_clear_filters_msg {
            get {
                return ResourceManager.GetString("err_clear_filters_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il dispositivo non è connesso alla rete. Abilitare la connessione e riprovare..
        /// </summary>
        internal static string err_device_offline_msg {
            get {
                return ResourceManager.GetString("err_device_offline_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo email non presente..
        /// </summary>
        internal static string err_email_missing_msg {
            get {
                return ResourceManager.GetString("err_email_missing_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile contattare via email il cliente..
        /// </summary>
        internal static string err_email_missing_title {
            get {
                return ResourceManager.GetString("err_email_missing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autenticazione fallita. Controllare le credenziali e riprovare..
        /// </summary>
        internal static string err_login {
            get {
                return ResourceManager.GetString("err_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;operazione di logout..
        /// </summary>
        internal static string err_logout {
            get {
                return ResourceManager.GetString("err_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di rete. Verificare la propria connessione e riprovare..
        /// </summary>
        internal static string err_offline_msg {
            get {
                return ResourceManager.GetString("err_offline_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di connessione..
        /// </summary>
        internal static string err_offline_title {
            get {
                return ResourceManager.GetString("err_offline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Numero di telefono non presente..
        /// </summary>
        internal static string err_phonenumber_missing_msg {
            get {
                return ResourceManager.GetString("err_phonenumber_missing_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile contattare telefonicamente il cliente..
        /// </summary>
        internal static string err_phonenumber_missing_title {
            get {
                return ResourceManager.GetString("err_phonenumber_missing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;aggiornamento dei dati..
        /// </summary>
        internal static string err_save {
            get {
                return ResourceManager.GetString("err_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;installazione del servizio di sincronizzazione..
        /// </summary>
        internal static string err_syncservice {
            get {
                return ResourceManager.GetString("err_syncservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; in corso la prima sincronizzazione dei dati. Si prega di attendere..
        /// </summary>
        internal static string err_syncservicenotcompleted {
            get {
                return ResourceManager.GetString("err_syncservicenotcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per procedere con il login è necessario effettuare la prima sincronizzazione dei dati. Lanciare l&apos;app SyncService ed attendere..
        /// </summary>
        internal static string err_syncservicenotlaunched {
            get {
                return ResourceManager.GetString("err_syncservicenotlaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a www.google.com.
        /// </summary>
        internal static string remote_host {
            get {
                return ResourceManager.GetString("remote_host", resourceCulture);
            }
        }
    }
}
